/// The contents of this file are replaced by code generated by 
/// user configuration. 
/// See README for more details. 

#[cfg(not(feature = "no_custom"))]
use retina_subscriptiongen::subscription_type;

#[cfg(not(feature = "no_custom"))]
#[subscription_type] 
pub mod custom_data {
    pub struct SubscribableWrapper;
    pub struct Subscribed;
}

#[cfg(feature = "no_custom")]
pub mod custom_data {
    pub struct SubscribableWrapper;
    pub struct Subscribed;
}