[[subscriptions]]
filter = "dns"
datatypes = [
    "DnsTransaction",
    "CoreId"
]
callback = "dns_cb"

[[subscriptions]]
filter = "http"
datatypes = [
    "HttpTransaction",
    "CoreId"
]
callback = "http_cb"

[[subscriptions]]
filter = "tls"
datatypes = [
    "TlsHandshake",
    "CoreId"
]
callback = "tls_cb"

[[subscriptions]]
filter = "quic"
datatypes = [
    "QuicStream",
    "CoreId"
]
callback = "quic_cb"