# This configuration is an example to show how to use a DPDK virtual device
# for instance af_packet sockets, memory ring, or pcap-backed device.
# !!! Those virtual devices do not expose hardware capabilities, this is only
# intended for limited functional testing. !!!
# 
# See https://stanford-esrg.github.io/retina/retina_core/config/index.html
# for configuration options.

main_core = 0
nb_memory_channels = 6

[mempool]
    capacity = 8192
    cache_size = 512

[online]
    duration = 60
    nb_rxd = 32768
    promiscuous = true
    mtu = 65535
    hardware_assist = false
    dpdk_supl_args = ["--no-huge","--no-pci","-m 512M","--vdev=net_pcap0,iface=ens0"]

    [online.monitor.display]
        throughput = true
        mempool_usage = true
        port_stats = ["rx_good_packets",
                        "rx_good_bytes",
                        "rx_mbuf_allocation_errors",
                        "rx_phy_discard_packets",
                        "rx_missed_errors",
                        ]
    [online.monitor.log]
        directory = "./log"
        interval = 1000

    [[online.ports]]
        device = "net_pcap0"
        cores = [1]

[conntrack]
    max_connections = 10_000_000
    max_out_of_order = 500
    timeout_resolution = 100
    udp_inactivity_timeout = 60_000
    tcp_inactivity_timeout = 300_000
    tcp_establish_timeout = 5000
