subscriptions = [
    { filter = "http.user_agent ~ 'Mozilla.*'", datatype = "ZcFrame", callback = "packet_cb" },
    { filter = "ipv4 and tcp", datatype = "Connection", callback = "conn_cb" },
    { filter = "http.user_agent ~ 'Mozilla.*'", datatype = "HttpTransaction", callback = "http_cb" },
    { filter = "tls", datatype = "ZcFrame", callback = "packet_cb" },
    { filter = "udp.port != 80 and udp.port != 90", datatype = "ZcFrame", callback = "packet_cb" },
    ]