subscriptions = [
    { filter = "http.user_agent ~ 'Mozilla.*'", datatypes = ["ZcFrame", "CoreId"], callback = "packet_cb" },
    { filter = "ipv4 and http", datatypes = ["Connection", "SessionList"], callback = "conn_cb" },
    { filter = "http.user_agent ~ 'abc.*'", datatypes = ["Connection", "SessionList"], callback = "conn_cb" },
    { filter = "http.user_agent ~ 'def.*'", datatypes = ["Connection", "SessionList"], callback = "conn_cb" },
    { filter = "http.user_agent ~ 'Mozilla.*'", datatypes = ["HttpTransaction", "FiveTuple", "CoreId", "EtherType"], callback = "http_cb" },
    ]