subscriptions = [ "HttpTransaction", "Connection" ]

[packet_continue]
"FrameContinue" = [ "ipv4" ]

[packet_filter]
"ConnFilter | ConnParse" = [ "ipv4.addr = 16.0.0.0/24 and tcp", "tcp.port > 60000 and ipv4" ]

[connection_filter]
"SessionParse (T) | SessionDeliverConn (T)" = [ "ipv4.addr = 16.0.0.0/24 and http", "tcp.port = 80 and http", "tcp.port = 100 and http" ]
"ConnDataTrack (T)" = [ "tcp.port > 60000 and ipv4" ]

[[connection_deliver]]
filter = "tcp.port > 60000 and ipv4"
datatype = "Connection"
callback = "tcp_port_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.0/24 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.1 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.2 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.3 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.4 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.5 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.6 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.7 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.8 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.9 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.10 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.11 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.12 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.13 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.14 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.15 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.16 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.17 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.18 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.19 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.20 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.16 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.22 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.23 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.24 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.25 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.26 and http"
datatype = "HttpTransaction"
callback = "http_cb"


[[session_deliver]]
filter = "ipv4.addr = 16.0.0.27 and http"
datatype = "HttpTransaction"
callback = "http_cb"


[[session_deliver]]
filter = "ipv4.addr = 16.0.0.28 and http"
datatype = "HttpTransaction"
callback = "http_cb"


[[session_deliver]]
filter = "ipv4.addr = 16.0.0.29 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.30 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.31 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.32 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.33 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.34 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.35 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.36 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.37 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.38 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.39 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.40 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.41 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.42 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.43 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.44 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.45 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.46 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.47 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.48 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "ipv4.addr = 16.0.0.49 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "tcp.port = 80 and http"
datatype = "HttpTransaction"
callback = "http_cb"

[[session_deliver]]
filter = "tcp.port = 100 and http"
datatype = "HttpTransaction"
callback = "http_cb"

