subscriptions = [
    "HttpTransaction",
    "Connection",
    "SubscribedSession"
]
connection_deliver = [
    { filter = "", datatype = "SubscribedSession", callback = "default_cb" },
]

[packet_continue]
"FrameContinue" = [
    "ipv4",
]

[packet_filter]
"ConnDataTrack (T)" = [
    "ipv4",
]