subscriptions = [
    "Connection",
]
connection_deliver = [
    { filter = '''tls.sni ~ '(.+?\.)?nflxvideo\.net'''', datatype = "Connection", callback = "netflix_cb" },
    { filter = '''tls.sni ~ '(.+?\\.)?h264\\.io'''', datatype = "Connection", callback = "max_cb" },
]

[packet_continue]
"Packet::Track" = [
    "tcp",
]

[packet_filter]
"ConnFilter | ConnParse | ConnDataTrack" = [
    "tcp",
]

[connection_filter]
"SessionParse | SessionFilter | ConnDataTrack" = [
    "tls",
]

[session_filter]
"ConnDataTrack (T)" = [
    '''tls.sni ~ '(.+?\.)?nflxvideo\.net'''',
    '''tls.sni ~ '(.+?\\.)?h264\\.io''''
]
